on:
  workflow_dispatch:
    inputs:
      content:
        required: true
jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: action
        uses: ./
        with:
          content: ${{ inputs.content }}
      - name: Debug print
        run: |
          echo 'frontMatterAsJson: ${{ steps.action.outputs.frontMatterAsJson }}'
          echo 'body: ${{ steps.action.outputs.body }}'
